[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]
eyre = "0.6.12"
axum = "0.8.8"
clap = { version = "4", features = ["derive"] }
console-subscriber = "0.5.0"
opentelemetry = "0.31"
opentelemetry_sdk = { version = "0.31", features = ["rt-tokio"] }
opentelemetry-stdout = { version = "0.31.0", features = ["metrics"] }
opentelemetry-appender-log = { version = "0.31.0", features = ["spec_unstable_logs_enabled", "with-serde"]}
opentelemetry-semantic-conventions = { version = "0.31.0", features = ["semconv_experimental"] }
opentelemetry-otlp = { version = "0.31.0", features = ["grpc-tonic", "metrics", "trace", "logs"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json"] }
tracing-opentelemetry = "0.32.1"
tower-http = { version = "0.6.8", features = ["trace", "sensitive-headers", "compression-zstd", "compression-br", "compression-gzip", "propagate-header"] }
tower = "0.5.3"
tracing-core = "0.1.36"
nanoid = "0.4.0"
dotenvy = { version = "0.15.7", features = ["clap"] }

[dev-dependencies]
reqwest = "0.13"
eyre = "0.6.12"
thiserror = "1.0"
